# Generated by Django 3.1.7 on 2021-03-29 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('for_everyone', models.BooleanField(default=False)),
                ('member_one', models.CharField(max_length=50)),
                ('member_two', models.CharField(max_length=50)),
                ('member_three', models.CharField(max_length=50)),
            ],
        ),
    ]
