# Generated by Django 3.1.7 on 2021-03-29 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questboard', '0003_quest_questboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quest',
        ),
    ]
